services:

  postgres:
    container_name: example-postgres
    build:
      dockerfile: ./docker/postgres/Dockerfile
    command: [
      "postgres",
      "-c", "log_destination=stderr",
      "-c", "wal_level=logical",
      "-c", "max_wal_senders=10",
      "-c", "max_replication_slots=10",
    ]
    ports:
      - "5432:5432"
    restart: always
    shm_size: 4g
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    networks:
      - example

networks:
  example:
    driver: bridge

volumes:
  postgres_data:

